class PRBS7Generator:
    """
    Generates deterministic PRBS7 binary patterns using
    a 7-bit Linear Feedback Shift Register (LFSR).

    Purpose:
        Used for validation scenarios involving:
        - SERDES stress testing
        - signal integrity analysis
        - BER-style validation
        - transition-rich data generation
        - high-speed interface validation

    Output:
        Raw binary byte stream.
    """

    pattern_name = "PRBS7"
    deterministic = True
    pattern_type = "PSEUDO_RANDOM"

    REGISTER_WIDTH = 7
    MAX_REGISTER_VALUE = 0x7F

    def __init__(
        self,
        size_in_bytes: int,
        seed_value: int
    ):
        """
        Initialize PRBS7 generator configuration.

        Args:
            size_in_bytes (int):
                Total size of generated pattern in bytes.

            seed_value (int):
                Initial non-zero LFSR seed value.
        """

        if not isinstance(size_in_bytes, int):
            raise TypeError("size_in_bytes must be an integer.")

        if size_in_bytes <= 0:
            raise ValueError("size_in_bytes must be greater than zero.")

        if not isinstance(seed_value, int):
            raise TypeError("seed_value must be an integer.")

        if not (1 <= seed_value <= self.MAX_REGISTER_VALUE):
            raise ValueError(
                "seed_value must be between 1 and 127."
            )

        self.size_in_bytes = size_in_bytes
        self.seed_value = seed_value

    def generate(self) -> bytes:
        """
        Generate PRBS7 binary pattern.

        Returns:
            bytes:
                PRBS7-generated byte stream.
        """

        generated_data = bytearray()

        lfsr = self.seed_value

        for _ in range(self.size_in_bytes):

            current_byte = 0

            for bit_position in range(8):

                output_bit = lfsr & 0x01

                current_byte |= (output_bit << bit_position)

                feedback_bit = (
                    ((lfsr >> 6) ^ (lfsr >> 5)) & 0x01
                )

                lfsr = (
                    ((lfsr << 1) | feedback_bit)
                    & self.MAX_REGISTER_VALUE
                )

            generated_data.append(current_byte)

        return bytes(generated_data)